[project]
name = "telegram-post-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "dotenv>=0.9.9",
    "halo>=0.0.31",
    "pyrogram>=2.0.106",
    "tgcrypto>=1.2.5",
]
